# Generated by Django 3.2.6 on 2021-08-15 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('part_number', models.CharField(max_length=9)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('year_quotated', models.IntegerField(default=1)),
                ('month_quotated', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('BOM_registered', models.BooleanField(default=False)),
            ],
        ),
    ]
