# Generated by Django 3.2.6 on 2021-08-15 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmod',
            name='month_quotated',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='pmod',
            name='name',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('[a-zA-Z]{2-3}[0-9]{2-3}', 'Only PMod name allowed')]),
        ),
        migrations.AlterField(
            model_name='pmod',
            name='part_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('[a-zA-Z]{1}[0-9]{7}[a-zA-Z]{1}', 'Only PMod part number allowed')]),
        ),
        migrations.AlterField(
            model_name='pmod',
            name='year_quotated',
            field=models.IntegerField(default=2021),
        ),
    ]
