# Generated by Django 3.2.6 on 2021-08-15 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmods', '0002_auto_20210815_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmod',
            name='name',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('[a-zA-Z]{2,3}[0-9]{2,3}', 'Only PMod name allowed')]),
        ),
    ]
